- name: Set MaxSize for Security log
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\EventLog\Security
    name: MaxSize
    data: "{{ max_log_size }}"
    type: dword
  notify: Restart Event Log Service

- name: Set Retention policy
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\EventLog\Security
    name: Retention
    data: "{{ retention_policy }}"
    type: dword

